package management

import "github.com/themurtez/go-valuate/financial"

// TopIssueSeverity is this section's own three-level urgency scale, the
// common scale every contributing sibling's own severity/flag type is
// translated onto — mirroring portfolio/diagnostics.Severity's identical
// role of normalizing several sibling packages' distinct severity types
// under one uniform scale.
type TopIssueSeverity string

const (
	TopIssueSeverityInfo     TopIssueSeverity = "info"
	TopIssueSeverityWarning  TopIssueSeverity = "warning"
	TopIssueSeverityCritical TopIssueSeverity = "critical"
)

// TopIssueSource identifies which Input field a TopIssue was translated
// from.
type TopIssueSource string

const (
	TopIssueSourceAnomalies TopIssueSource = "anomalies"
	TopIssueSourceQoE       TopIssueSource = "qoe"
	TopIssueSourceDebt      TopIssueSource = "debt"
	TopIssueSourceCovenants TopIssueSource = "covenants"
)

// TopIssue is one already-detected finding from a contributing sibling
// package (analytics/anomalies.Anomaly, analytics/qoe.Flag,
// analytics/debt.Flag, or a breached analytics/covenants.TestResult),
// translated onto this section's own Severity scale and ordered fields —
// never a new detection rule of this package's own.
type TopIssue struct {
	// Source names which Input field this issue came from.
	Source TopIssueSource `json:"source"`
	// Code echoes the source package's own stable code verbatim (e.g.
	// anomalies.RuleCode's string value, qoe.FlagCode's string value,
	// debt.FlagCode's string value, or the covenant's CovenantID), copied
	// as a plain string so this package need not import four different
	// code types for one field.
	Code string `json:"code"`
	// Severity is Code's originating finding's severity, translated onto
	// TopIssueSeverity.
	Severity TopIssueSeverity `json:"severity"`
	// Period is the period this issue concerns, when the source finding is
	// period-specific.
	Period financial.Period `json:"period,omitempty"`
	// Message is a short, human-readable statement of the issue, copied
	// verbatim from the source finding's own Explanation/Message field
	// (never re-generated by this package).
	Message string `json:"message"`
}

// TopIssuesSummary rolls TopIssues up by Severity and Source — the
// structured counterpart to scanning TopIssues by hand, mirroring
// analytics/anomalies.Summary's identical rollup-by-code/by-severity shape.
type TopIssuesSummary struct {
	Total int `json:"total"`
	// BySeverity maps each TopIssueSeverity present in TopIssues to its
	// count. Always has an entry for every severity that appears at least
	// once; never a zero-count entry for a severity that did not occur.
	BySeverity map[TopIssueSeverity]int `json:"by_severity,omitempty"`
	// BySource maps each TopIssueSource present in TopIssues to its count,
	// same zero-omission rule as BySeverity.
	BySource map[TopIssueSource]int `json:"by_source,omitempty"`
	// ReviewRecommended is true when Total > 0 — mirrors
	// analytics/anomalies.Summary.ReviewRecommended's identical rule.
	ReviewRecommended bool `json:"review_recommended"`
}

// TopIssues is the top anomalies/issues section: a merged, ordered view of
// already-detected findings from Input.Anomalies, Input.QoE.Flags,
// Input.Debt.Flags, and breached/near-breached entries in
// Input.Covenants.Tests.
type TopIssues struct {
	// Available is true when at least one contributing Input field
	// (Anomalies, QoE, Debt, Covenants) was itself Available.
	Available bool `json:"available"`
	// Issues is every translated issue, ordered by Severity (critical,
	// warning, info), then by Source declaration order
	// (anomalies, qoe, debt, covenants), then by the source slice's own order —
	// see buildTopIssues.
	Issues  []TopIssue       `json:"issues,omitempty"`
	Summary TopIssuesSummary `json:"summary"`
}
