// Conservative, deterministic image preprocessing ahead of OCR. Every
// transformation here is opt-in (via PreprocessOptions), individually
// testable, and does no ML-based enhancement of any kind — this package
// only ever applies well-understood, fully deterministic pixel
// transformations (grayscale conversion, linear contrast stretch, a fixed
// intensity threshold for binarization). Per the task contract: "do not
// over-process by default."
package pdf

import (
	"image"
	"image/color"

	"github.com/themurtez/go-valuate/ingestion"
)

// PreprocessOptions controls which deterministic preprocessing steps run
// before an image is handed to an OCR engine. Every field defaults to
// "off" (the zero value): OCR runs against the dominant page image
// completely unmodified unless a caller explicitly opts into a step,
// matching the "do not over-process by default" requirement.
type PreprocessOptions struct {
	// Grayscale converts the image to 8-bit grayscale before OCR. Most
	// scanned financial statements are already effectively monochrome
	// text on a white background, so this is often a no-op in practice,
	// but is applied unconditionally when requested rather than
	// conditionally skipped for an already-gray-looking image (keeping
	// behavior simple and fully deterministic).
	Grayscale bool
	// ContrastStretch, when true, applies a linear min/max contrast
	// stretch (the image's own observed darkest/lightest gray values are
	// remapped to 0/255) — a deterministic, well-understood normalization
	// that improves legibility for a scan with a narrow/washed-out
	// intensity range, without any content-aware/ML enhancement. Requires
	// Grayscale (applied to the grayscale conversion's output) — set both
	// together.
	ContrastStretch bool
	// Threshold, when non-zero (1-255), binarizes the image to pure
	// black/white at this fixed gray-level cutoff (every pixel at or
	// above Threshold becomes white, every pixel below becomes black).
	// Fixed-threshold binarization, never an adaptive/ML method. Requires
	// Grayscale.
	Threshold uint8
}

// Preprocess applies the requested deterministic steps to img, in a fixed
// order (grayscale, then contrast stretch, then threshold — each stage
// operates on the PREVIOUS stage's output, never the original image
// directly, so combining steps behaves exactly as their individual
// descriptions promise), returning the possibly-transformed image and any
// warnings (currently none are generated by preprocessing itself; the
// return shape matches this package's other warning-producing stages for
// consistency and future extension). With a zero-value PreprocessOptions,
// img is returned completely unmodified (same underlying image, no copy),
// matching "do not over-process by default."
func Preprocess(img image.Image, opts PreprocessOptions) (image.Image, []ingestion.Warning) {
	if !opts.Grayscale && !opts.ContrastStretch && opts.Threshold == 0 {
		return img, nil
	}

	var gray *image.Gray
	if opts.Grayscale || opts.ContrastStretch || opts.Threshold != 0 {
		gray = toGrayscale(img)
	}

	if opts.ContrastStretch {
		gray = contrastStretch(gray)
	}

	if opts.Threshold != 0 {
		gray = binarize(gray, opts.Threshold)
	}

	return gray, nil
}

// toGrayscale converts img to 8-bit grayscale using Go's standard
// color.GrayModel conversion (a fixed, well-known luminance-weighted
// formula — no ML, no content-aware adjustment).
func toGrayscale(img image.Image) *image.Gray {
	b := img.Bounds()
	out := image.NewGray(b)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			out.Set(x, y, img.At(x, y))
		}
	}
	return out
}

// contrastStretch remaps gray's observed [min, max] intensity range
// linearly onto [0, 255]. If the image is already full-range (or
// perfectly flat, min == max), it is returned unchanged — a flat image has
// no contrast to stretch, and stretching it would be either a no-op or
// (for a perfectly uniform image) undefined division, so this case is
// explicitly guarded rather than risking a divide-by-zero.
func contrastStretch(gray *image.Gray) *image.Gray {
	b := gray.Bounds()
	min, max := uint8(255), uint8(0)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			v := gray.GrayAt(x, y).Y
			if v < min {
				min = v
			}
			if v > max {
				max = v
			}
		}
	}
	if max <= min {
		return gray
	}

	out := image.NewGray(b)
	rangeF := float64(max - min)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			v := gray.GrayAt(x, y).Y
			stretched := float64(v-min) / rangeF * 255.0
			out.SetGray(x, y, color.Gray{Y: uint8(clamp0to255(stretched))})
		}
	}
	return out
}

// binarize converts gray to pure black/white at a fixed threshold: every
// pixel at or above threshold becomes white (255), every pixel below
// becomes black (0). A fixed global threshold, never adaptive/local or
// ML-based, matching the task contract's "optional thresholding/
// binarization" as a conservative deterministic step.
func binarize(gray *image.Gray, threshold uint8) *image.Gray {
	b := gray.Bounds()
	out := image.NewGray(b)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			v := gray.GrayAt(x, y).Y
			if v >= threshold {
				out.SetGray(x, y, color.Gray{Y: 255})
			} else {
				out.SetGray(x, y, color.Gray{Y: 0})
			}
		}
	}
	return out
}

func clamp0to255(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 255 {
		return 255
	}
	return v
}
